### ISSUE TITLE
The app does not seem to work 

### ISSUE THREAD

**Issue by loukesio** [nate-d-olson/snp_eval_shiny#1]
Hello :) 

It seems great what you are trying. 
I try to use the app but was not working. If you see it I am looking forward to seeing how it looks 

thank you :)

**Comment by nate-d-olson** [comment]
Sorry for the delay. I am no longer working on this project. Shinny has evolved a lot since I first developed the app. Your best bet is to download the code and try debugging it yourself. 
In case you had not see it, the app was part of a review paper that I co-authored a few years ago that will provide additional information about small variant validation, 10.3389/fgene.2015.00235.
